from .Rule_Creole_Ending_In_Ing import Rule_Creole_Ending_In_Ing
from .Rule_Creole_Th_Stopping_D import Rule_Creole_Th_Stopping_D
from .Rule_Creole_Th_Stopping_T import Rule_Creole_Th_Stopping_T
from .Rule_Creole_Sound_Omission_ST_To_S import Rule_Creole_Sound_Omission_ST_To_S
from .Rule_Creole_Sound_Omission_CT_To_C import Rule_Creole_Sound_Omission_CT_To_C
from .Rule_Creole_Sound_Omission_FT_To_F import Rule_Creole_Sound_Omission_FT_To_F
from .Rule_Creole_Sound_Omission_ND_To_N import Rule_Creole_Sound_Omission_ND_To_N
from .Rule_Creole_Sound_Omission_PT_To_P import Rule_Creole_Sound_Omission_PT_To_P
from .Rule_Creole_Sound_Omission_LD_To_L import Rule_Creole_Sound_Omission_LD_To_L
from .Rule_Creole_Sound_Omission_CT_To_C_Exception import Rule_Creole_Sound_Omission_CT_To_C_Exception

creole_rules_list = [
    Rule_Creole_Ending_In_Ing,
    Rule_Creole_Th_Stopping_D,
    Rule_Creole_Th_Stopping_T,
    Rule_Creole_Sound_Omission_ST_To_S,
    Rule_Creole_Sound_Omission_CT_To_C,
    Rule_Creole_Sound_Omission_FT_To_F,
    Rule_Creole_Sound_Omission_ND_To_N,
    Rule_Creole_Sound_Omission_PT_To_P,
    Rule_Creole_Sound_Omission_LD_To_L,
    Rule_Creole_Sound_Omission_CT_To_C_Exception,
]